language: java
jdk:
  - openjdk8
notifications:
  email:
    recipients:
      - gmlm60832@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 8d82ad9a-4843-4b6e-b282-31ae0d7a51bc
  app: backend-api-example
  on:
    repo: GinoLopez12/spring-boot-heroku



